#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Parachute

#include "Basic.hpp"

#include "ABP_Parachute_classes.hpp"
#include "ABP_Parachute_parameters.hpp"


namespace SDK
{

// Function ABP_Parachute.ABP_Parachute_C.ExecuteUbergraph_ABP_Parachute
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UABP_Parachute_C::ExecuteUbergraph_ABP_Parachute(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Parachute_C", "ExecuteUbergraph_ABP_Parachute");

	Params::ABP_Parachute_C_ExecuteUbergraph_ABP_Parachute Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Parachute.ABP_Parachute_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_TransitionResult_8AA3C9594065D00D1739DC8C27BE794B
// (BlueprintEvent)

void UABP_Parachute_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_TransitionResult_8AA3C9594065D00D1739DC8C27BE794B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Parachute_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_TransitionResult_8AA3C9594065D00D1739DC8C27BE794B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Parachute.ABP_Parachute_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_RotationOffsetBlendSpace_CF9DB4CA45BFB70346FCD19CDE83A9A8
// (BlueprintEvent)

void UABP_Parachute_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_RotationOffsetBlendSpace_CF9DB4CA45BFB70346FCD19CDE83A9A8()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Parachute_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_RotationOffsetBlendSpace_CF9DB4CA45BFB70346FCD19CDE83A9A8");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Parachute.ABP_Parachute_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_TransitionResult_08AC8CD648FF07A568A955BBB897ACEA
// (BlueprintEvent)

void UABP_Parachute_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_TransitionResult_08AC8CD648FF07A568A955BBB897ACEA()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Parachute_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_TransitionResult_08AC8CD648FF07A568A955BBB897ACEA");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Parachute.ABP_Parachute_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_ModifyBone_0D766A7843E2AB511705828BBC45830D
// (BlueprintEvent)

void UABP_Parachute_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_ModifyBone_0D766A7843E2AB511705828BBC45830D()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Parachute_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_ModifyBone_0D766A7843E2AB511705828BBC45830D");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Parachute.ABP_Parachute_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_ModifyBone_EEC6BE1042BF2A7DDFCCEFB87D8C4EC4
// (BlueprintEvent)

void UABP_Parachute_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_ModifyBone_EEC6BE1042BF2A7DDFCCEFB87D8C4EC4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Parachute_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_ModifyBone_EEC6BE1042BF2A7DDFCCEFB87D8C4EC4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Parachute.ABP_Parachute_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_ModifyBone_38CE55804D1402DCACC18CA00C9A8C3E
// (BlueprintEvent)

void UABP_Parachute_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_ModifyBone_38CE55804D1402DCACC18CA00C9A8C3E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Parachute_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_ModifyBone_38CE55804D1402DCACC18CA00C9A8C3E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Parachute.ABP_Parachute_C.AnimNotify_EnteredLocomotion
// (BlueprintCallable, BlueprintEvent)

void UABP_Parachute_C::AnimNotify_EnteredLocomotion()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Parachute_C", "AnimNotify_EnteredLocomotion");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Parachute.ABP_Parachute_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UABP_Parachute_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Parachute_C", "BlueprintUpdateAnimation");

	Params::ABP_Parachute_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Parachute.ABP_Parachute_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_TransitionResult_8E3F0229406AF5296B72E6A316B804A4
// (BlueprintEvent)

void UABP_Parachute_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_TransitionResult_8E3F0229406AF5296B72E6A316B804A4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Parachute_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parachute_AnimGraphNode_TransitionResult_8E3F0229406AF5296B72E6A316B804A4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Parachute.ABP_Parachute_C.CheckIfLanding
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UABP_Parachute_C::CheckIfLanding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Parachute_C", "CheckIfLanding");

	UObject::ProcessEvent(Func, nullptr);
}

}

