#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Boat_PG117_Animation

#include "Basic.hpp"

#include "Boat_PG117_Animation_classes.hpp"
#include "Boat_PG117_Animation_parameters.hpp"


namespace SDK
{

// Function Boat_PG117_Animation.Boat_PG117_Animation_C.ExecuteUbergraph_Boat_PG117_Animation
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBoat_PG117_Animation_C::ExecuteUbergraph_Boat_PG117_Animation(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Boat_PG117_Animation_C", "ExecuteUbergraph_Boat_PG117_Animation");

	Params::Boat_PG117_Animation_C_ExecuteUbergraph_Boat_PG117_Animation Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Boat_PG117_Animation.Boat_PG117_Animation_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBoat_PG117_Animation_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Boat_PG117_Animation_C", "BlueprintUpdateAnimation");

	Params::Boat_PG117_Animation_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Boat_PG117_Animation.Boat_PG117_Animation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Boat_PG117_Animation_AnimGraphNode_ModifyBone_8057CE8141CBA4DBCBB2FC8BC84934CE
// (BlueprintEvent)

void UBoat_PG117_Animation_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Boat_PG117_Animation_AnimGraphNode_ModifyBone_8057CE8141CBA4DBCBB2FC8BC84934CE()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Boat_PG117_Animation_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Boat_PG117_Animation_AnimGraphNode_ModifyBone_8057CE8141CBA4DBCBB2FC8BC84934CE");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Boat_PG117_Animation.Boat_PG117_Animation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Boat_PG117_Animation_AnimGraphNode_ModifyBone_23B5532142004C9B1C5E36A8005A6FD9
// (BlueprintEvent)

void UBoat_PG117_Animation_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Boat_PG117_Animation_AnimGraphNode_ModifyBone_23B5532142004C9B1C5E36A8005A6FD9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Boat_PG117_Animation_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Boat_PG117_Animation_AnimGraphNode_ModifyBone_23B5532142004C9B1C5E36A8005A6FD9");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Boat_PG117_Animation.Boat_PG117_Animation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Boat_PG117_Animation_AnimGraphNode_ModifyBone_64A4DFC849F2AC37DED7E693D6450034
// (BlueprintEvent)

void UBoat_PG117_Animation_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Boat_PG117_Animation_AnimGraphNode_ModifyBone_64A4DFC849F2AC37DED7E693D6450034()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Boat_PG117_Animation_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Boat_PG117_Animation_AnimGraphNode_ModifyBone_64A4DFC849F2AC37DED7E693D6450034");

	UObject::ProcessEvent(Func, nullptr);
}

}

