#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buggy_Wheel_RL

#include "Basic.hpp"

#include "Buggy_Wheel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buggy_Wheel_RL.Buggy_Wheel_RL_C
// 0x0000 (0x0200 - 0x0200)
class UBuggy_Wheel_RL_C final : public UBuggy_Wheel_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Buggy_Wheel_RL_C">();
	}
	static class UBuggy_Wheel_RL_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuggy_Wheel_RL_C>();
	}
};
static_assert(alignof(UBuggy_Wheel_RL_C) == 0x000008, "Wrong alignment on UBuggy_Wheel_RL_C");
static_assert(sizeof(UBuggy_Wheel_RL_C) == 0x000200, "Wrong size on UBuggy_Wheel_RL_C");

}

