#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CastingBarInfoTextWidget

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"
#include "TslGame_structs.hpp"


namespace SDK::Params
{

// Function CastingBarInfoTextWidget.CastingBarInfoTextWidget_C.ExecuteUbergraph_CastingBarInfoTextWidget
// 0x0088 (0x0088 - 0x0000)
struct CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsLastInputGamepad_ReturnValue;           // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         m__int_Variable;                                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          m__bool_Variable;                                  // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ATslCharacter*                          CallFunc_GetOwningShooterCharacter_ShooterCharacter; // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0018(0x0034)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UCastComponent*>                 CallFunc_GetComponentsByClass_ReturnValue;         // 0x0058(0x0010)(ZeroConstructor, ReferenceParm)
	class UCastComponent*                         CallFunc_Array_Get_Item;                           // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue2;                     // 0x0074(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0075(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ECastLevel                                    CallFunc_GetCastLevel_ReturnValue;                 // 0x0076(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0077(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsAnimationPlaying_ReturnValue;           // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79[0x3];                                       // 0x0079(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         m__int_Variable2;                                  // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsXBoxOnePlatform_NewParam;               // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_82[0x2];                                       // 0x0082(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Select_Default;                             // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget) == 0x000008, "Wrong alignment on CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget");
static_assert(sizeof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget) == 0x000088, "Wrong size on CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, EntryPoint) == 0x000000, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::EntryPoint' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, CallFunc_IsLastInputGamepad_ReturnValue) == 0x000004, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::CallFunc_IsLastInputGamepad_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, m__int_Variable) == 0x000008, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::m__int_Variable' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, m__bool_Variable) == 0x00000C, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::m__bool_Variable' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, CallFunc_GetOwningShooterCharacter_ShooterCharacter) == 0x000010, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::CallFunc_GetOwningShooterCharacter_ShooterCharacter' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, K2Node_Event_MyGeometry) == 0x000018, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, K2Node_Event_InDeltaTime) == 0x00004C, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, CallFunc_IsValid_ReturnValue) == 0x000050, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, CallFunc_GetComponentsByClass_ReturnValue) == 0x000058, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::CallFunc_GetComponentsByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, CallFunc_Array_Get_Item) == 0x000068, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, CallFunc_Array_Length_ReturnValue) == 0x000070, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, CallFunc_IsValid_ReturnValue2) == 0x000074, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::CallFunc_IsValid_ReturnValue2' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, CallFunc_Greater_IntInt_ReturnValue) == 0x000075, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, CallFunc_GetCastLevel_ReturnValue) == 0x000076, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::CallFunc_GetCastLevel_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000077, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, CallFunc_IsAnimationPlaying_ReturnValue) == 0x000078, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::CallFunc_IsAnimationPlaying_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, m__int_Variable2) == 0x00007C, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::m__int_Variable2' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, CallFunc_IsXBoxOnePlatform_NewParam) == 0x000080, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::CallFunc_IsXBoxOnePlatform_NewParam' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, CallFunc_BooleanOR_ReturnValue) == 0x000081, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget, K2Node_Select_Default) == 0x000084, "Member 'CastingBarInfoTextWidget_C_ExecuteUbergraph_CastingBarInfoTextWidget::K2Node_Select_Default' has a wrong offset!");

// Function CastingBarInfoTextWidget.CastingBarInfoTextWidget_C.Tick
// 0x0038 (0x0038 - 0x0000)
struct CastingBarInfoTextWidget_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0034)(Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0034(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CastingBarInfoTextWidget_C_Tick) == 0x000004, "Wrong alignment on CastingBarInfoTextWidget_C_Tick");
static_assert(sizeof(CastingBarInfoTextWidget_C_Tick) == 0x000038, "Wrong size on CastingBarInfoTextWidget_C_Tick");
static_assert(offsetof(CastingBarInfoTextWidget_C_Tick, MyGeometry) == 0x000000, "Member 'CastingBarInfoTextWidget_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_Tick, InDeltaTime) == 0x000034, "Member 'CastingBarInfoTextWidget_C_Tick::InDeltaTime' has a wrong offset!");

// Function CastingBarInfoTextWidget.CastingBarInfoTextWidget_C.GetCastName
// 0x00D8 (0x00D8 - 0x0000)
struct CastingBarInfoTextWidget_C_GetCastName final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	bool                                          m__bool_Variable;                                  // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          m__bool_Variable2;                                 // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A[0x6];                                       // 0x001A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ATslCharacter*                          CallFunc_GetOwningShooterCharacter_ShooterCharacter; // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATslPlayerController*                   K2Node_DynamicCast_AsTsl_Player_Controller;        // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetOtherCastingName_ReturnValue;          // 0x0048(0x0018)()
	bool                                          CallFunc_IsGroggying_ReturnValue;                  // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsSpectating_ReturnValue;                 // 0x0062(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0063(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_65[0x3];                                       // 0x0065(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default;                             // 0x0068(0x0018)()
	TArray<class UCastComponent*>                 CallFunc_GetComponentsByClass_ReturnValue;         // 0x0080(0x0010)(ZeroConstructor, ReferenceParm)
	class UCastComponent*                         CallFunc_Array_Get_Item;                           // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue2;                     // 0x009C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x009D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9E[0x2];                                       // 0x009E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetCastName_ReturnValue;                  // 0x00A0(0x0018)()
	bool                                          CallFunc_TextIsEmpty_ReturnValue2;                 // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue2;                 // 0x00B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_BA[0x6];                                       // 0x00BA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select2_Default;                            // 0x00C0(0x0018)()
};
static_assert(alignof(CastingBarInfoTextWidget_C_GetCastName) == 0x000008, "Wrong alignment on CastingBarInfoTextWidget_C_GetCastName");
static_assert(sizeof(CastingBarInfoTextWidget_C_GetCastName) == 0x0000D8, "Wrong size on CastingBarInfoTextWidget_C_GetCastName");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, ReturnValue) == 0x000000, "Member 'CastingBarInfoTextWidget_C_GetCastName::ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, m__bool_Variable) == 0x000018, "Member 'CastingBarInfoTextWidget_C_GetCastName::m__bool_Variable' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, m__bool_Variable2) == 0x000019, "Member 'CastingBarInfoTextWidget_C_GetCastName::m__bool_Variable2' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_GetOwningShooterCharacter_ShooterCharacter) == 0x000020, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_GetOwningShooterCharacter_ShooterCharacter' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_GetOwningPlayer_ReturnValue) == 0x000028, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_IsValid_ReturnValue) == 0x000030, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, K2Node_DynamicCast_AsTsl_Player_Controller) == 0x000038, "Member 'CastingBarInfoTextWidget_C_GetCastName::K2Node_DynamicCast_AsTsl_Player_Controller' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, K2Node_DynamicCast_bSuccess) == 0x000040, "Member 'CastingBarInfoTextWidget_C_GetCastName::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_GetOtherCastingName_ReturnValue) == 0x000048, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_GetOtherCastingName_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_IsGroggying_ReturnValue) == 0x000060, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_IsGroggying_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_TextIsEmpty_ReturnValue) == 0x000061, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_IsSpectating_ReturnValue) == 0x000062, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_IsSpectating_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_Not_PreBool_ReturnValue) == 0x000063, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_BooleanOR_ReturnValue) == 0x000064, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, K2Node_Select_Default) == 0x000068, "Member 'CastingBarInfoTextWidget_C_GetCastName::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_GetComponentsByClass_ReturnValue) == 0x000080, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_GetComponentsByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_Array_Get_Item) == 0x000090, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_Array_Length_ReturnValue) == 0x000098, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_IsValid_ReturnValue2) == 0x00009C, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_IsValid_ReturnValue2' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_Greater_IntInt_ReturnValue) == 0x00009D, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_GetCastName_ReturnValue) == 0x0000A0, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_GetCastName_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_TextIsEmpty_ReturnValue2) == 0x0000B8, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_TextIsEmpty_ReturnValue2' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, CallFunc_Not_PreBool_ReturnValue2) == 0x0000B9, "Member 'CastingBarInfoTextWidget_C_GetCastName::CallFunc_Not_PreBool_ReturnValue2' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetCastName, K2Node_Select2_Default) == 0x0000C0, "Member 'CastingBarInfoTextWidget_C_GetCastName::K2Node_Select2_Default' has a wrong offset!");

// Function CastingBarInfoTextWidget.CastingBarInfoTextWidget_C.GetVisibility_0
// 0x0048 (0x0048 - 0x0000)
struct CastingBarInfoTextWidget_C_GetVisibility_0 final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATslCharacter*                          CallFunc_GetOwningShooterCharacter_ShooterCharacter; // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UCastComponent*>                 CallFunc_GetComponentsByClass_ReturnValue;         // 0x0018(0x0010)(ZeroConstructor, ReferenceParm)
	class UCastComponent*                         CallFunc_Array_Get_Item;                           // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue2;                     // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0035(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_36[0x2];                                       // 0x0036(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_GetCastObject_ReturnValue;                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue3;                     // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CastingBarInfoTextWidget_C_GetVisibility_0) == 0x000008, "Wrong alignment on CastingBarInfoTextWidget_C_GetVisibility_0");
static_assert(sizeof(CastingBarInfoTextWidget_C_GetVisibility_0) == 0x000048, "Wrong size on CastingBarInfoTextWidget_C_GetVisibility_0");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetVisibility_0, ReturnValue) == 0x000000, "Member 'CastingBarInfoTextWidget_C_GetVisibility_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetVisibility_0, CallFunc_GetOwningShooterCharacter_ShooterCharacter) == 0x000008, "Member 'CastingBarInfoTextWidget_C_GetVisibility_0::CallFunc_GetOwningShooterCharacter_ShooterCharacter' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetVisibility_0, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'CastingBarInfoTextWidget_C_GetVisibility_0::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetVisibility_0, CallFunc_GetComponentsByClass_ReturnValue) == 0x000018, "Member 'CastingBarInfoTextWidget_C_GetVisibility_0::CallFunc_GetComponentsByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetVisibility_0, CallFunc_Array_Get_Item) == 0x000028, "Member 'CastingBarInfoTextWidget_C_GetVisibility_0::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetVisibility_0, CallFunc_Array_Length_ReturnValue) == 0x000030, "Member 'CastingBarInfoTextWidget_C_GetVisibility_0::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetVisibility_0, CallFunc_IsValid_ReturnValue2) == 0x000034, "Member 'CastingBarInfoTextWidget_C_GetVisibility_0::CallFunc_IsValid_ReturnValue2' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetVisibility_0, CallFunc_Greater_IntInt_ReturnValue) == 0x000035, "Member 'CastingBarInfoTextWidget_C_GetVisibility_0::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetVisibility_0, CallFunc_GetCastObject_ReturnValue) == 0x000038, "Member 'CastingBarInfoTextWidget_C_GetVisibility_0::CallFunc_GetCastObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_GetVisibility_0, CallFunc_IsValid_ReturnValue3) == 0x000040, "Member 'CastingBarInfoTextWidget_C_GetVisibility_0::CallFunc_IsValid_ReturnValue3' has a wrong offset!");

// Function CastingBarInfoTextWidget.CastingBarInfoTextWidget_C.OnPrepass_0
// 0x0008 (0x0008 - 0x0000)
struct CastingBarInfoTextWidget_C_OnPrepass_0 final
{
public:
	class UWidget*                                BoundWidget;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CastingBarInfoTextWidget_C_OnPrepass_0) == 0x000008, "Wrong alignment on CastingBarInfoTextWidget_C_OnPrepass_0");
static_assert(sizeof(CastingBarInfoTextWidget_C_OnPrepass_0) == 0x000008, "Wrong size on CastingBarInfoTextWidget_C_OnPrepass_0");
static_assert(offsetof(CastingBarInfoTextWidget_C_OnPrepass_0, BoundWidget) == 0x000000, "Member 'CastingBarInfoTextWidget_C_OnPrepass_0::BoundWidget' has a wrong offset!");

// Function CastingBarInfoTextWidget.CastingBarInfoTextWidget_C.Get_KeyText_Text_0
// 0x0050 (0x0050 - 0x0000)
struct CastingBarInfoTextWidget_C_Get_KeyText_Text_0 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	struct FTslInputKey                           CallFunc_GetActionKey_ReturnValue;                 // 0x0018(0x0020)()
	class FText                                   CallFunc_GetKeyName_ReturnValue;                   // 0x0038(0x0018)()
};
static_assert(alignof(CastingBarInfoTextWidget_C_Get_KeyText_Text_0) == 0x000008, "Wrong alignment on CastingBarInfoTextWidget_C_Get_KeyText_Text_0");
static_assert(sizeof(CastingBarInfoTextWidget_C_Get_KeyText_Text_0) == 0x000050, "Wrong size on CastingBarInfoTextWidget_C_Get_KeyText_Text_0");
static_assert(offsetof(CastingBarInfoTextWidget_C_Get_KeyText_Text_0, ReturnValue) == 0x000000, "Member 'CastingBarInfoTextWidget_C_Get_KeyText_Text_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_Get_KeyText_Text_0, CallFunc_GetActionKey_ReturnValue) == 0x000018, "Member 'CastingBarInfoTextWidget_C_Get_KeyText_Text_0::CallFunc_GetActionKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_Get_KeyText_Text_0, CallFunc_GetKeyName_ReturnValue) == 0x000038, "Member 'CastingBarInfoTextWidget_C_Get_KeyText_Text_0::CallFunc_GetKeyName_ReturnValue' has a wrong offset!");

// Function CastingBarInfoTextWidget.CastingBarInfoTextWidget_C.On_CastingInfoCancelMsgBox_Prepass_0
// 0x0008 (0x0008 - 0x0000)
struct CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgBox_Prepass_0 final
{
public:
	class UWidget*                                BoundWidget;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgBox_Prepass_0) == 0x000008, "Wrong alignment on CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgBox_Prepass_0");
static_assert(sizeof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgBox_Prepass_0) == 0x000008, "Wrong size on CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgBox_Prepass_0");
static_assert(offsetof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgBox_Prepass_0, BoundWidget) == 0x000000, "Member 'CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgBox_Prepass_0::BoundWidget' has a wrong offset!");

// Function CastingBarInfoTextWidget.CastingBarInfoTextWidget_C.Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0
// 0x0044 (0x0044 - 0x0000)
struct CastingBarInfoTextWidget_C_Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0 final
{
public:
	struct FLinearColor                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	bool                                          m__bool_Variable;                                  // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           m__struct_Variable;                                // 0x0014(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FLinearColor                           m__struct_Variable2;                               // 0x0024(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FLinearColor                           K2Node_Select_Default;                             // 0x0034(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CastingBarInfoTextWidget_C_Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0) == 0x000004, "Wrong alignment on CastingBarInfoTextWidget_C_Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0");
static_assert(sizeof(CastingBarInfoTextWidget_C_Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0) == 0x000044, "Wrong size on CastingBarInfoTextWidget_C_Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0");
static_assert(offsetof(CastingBarInfoTextWidget_C_Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0, ReturnValue) == 0x000000, "Member 'CastingBarInfoTextWidget_C_Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0, m__bool_Variable) == 0x000010, "Member 'CastingBarInfoTextWidget_C_Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0::m__bool_Variable' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0, m__struct_Variable) == 0x000014, "Member 'CastingBarInfoTextWidget_C_Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0::m__struct_Variable' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0, m__struct_Variable2) == 0x000024, "Member 'CastingBarInfoTextWidget_C_Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0::m__struct_Variable2' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0, K2Node_Select_Default) == 0x000034, "Member 'CastingBarInfoTextWidget_C_Get_CastingInfoCancelMsgLayer_ContentColorAndOpacity_0::K2Node_Select_Default' has a wrong offset!");

// Function CastingBarInfoTextWidget.CastingBarInfoTextWidget_C.On_CastingInfoCancelMsgLayer_Prepass_0
// 0x0028 (0x0028 - 0x0000)
struct CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0 final
{
public:
	class UWidget*                                BoundWidget;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          m__bool_Variable;                                  // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              m__byte_Variable;                                  // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              m__byte_Variable2;                                 // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B[0x5];                                        // 0x000B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class ATslPlayerController*                   K2Node_DynamicCast_AsTsl_Player_Controller;        // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsSpectating_ReturnValue;                 // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsGroggying_ReturnValue;                  // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0023(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0) == 0x000008, "Wrong alignment on CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0");
static_assert(sizeof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0) == 0x000028, "Wrong size on CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0");
static_assert(offsetof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0, BoundWidget) == 0x000000, "Member 'CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0::BoundWidget' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0, m__bool_Variable) == 0x000008, "Member 'CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0::m__bool_Variable' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0, m__byte_Variable) == 0x000009, "Member 'CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0::m__byte_Variable' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0, m__byte_Variable2) == 0x00000A, "Member 'CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0::m__byte_Variable2' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0, CallFunc_GetOwningPlayer_ReturnValue) == 0x000010, "Member 'CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0, K2Node_DynamicCast_AsTsl_Player_Controller) == 0x000018, "Member 'CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0::K2Node_DynamicCast_AsTsl_Player_Controller' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0, CallFunc_IsSpectating_ReturnValue) == 0x000021, "Member 'CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0::CallFunc_IsSpectating_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0, CallFunc_IsGroggying_ReturnValue) == 0x000022, "Member 'CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0::CallFunc_IsGroggying_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0, CallFunc_BooleanOR_ReturnValue) == 0x000023, "Member 'CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0, K2Node_Select_Default) == 0x000024, "Member 'CastingBarInfoTextWidget_C_On_CastingInfoCancelMsgLayer_Prepass_0::K2Node_Select_Default' has a wrong offset!");

}

