#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CinematicCamera

#include "Basic.hpp"


namespace SDK::Params
{

// Function CinematicCamera.CineCameraActor.GetCineCameraComponent
// 0x0008 (0x0008 - 0x0000)
struct CineCameraActor_GetCineCameraComponent final
{
public:
	class UCineCameraComponent*                   ReturnValue;                                       // 0x0000(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(CineCameraActor_GetCineCameraComponent) == 0x000008, "Wrong alignment on CineCameraActor_GetCineCameraComponent");
static_assert(sizeof(CineCameraActor_GetCineCameraComponent) == 0x000008, "Wrong size on CineCameraActor_GetCineCameraComponent");
static_assert(offsetof(CineCameraActor_GetCineCameraComponent, ReturnValue) == 0x000000, "Member 'CineCameraActor_GetCineCameraComponent::ReturnValue' has a wrong offset!");

}

