#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ComboBoxOption

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct ComboBoxOption.ComboBoxOption
// 0x0028 (0x0028 - 0x0000)
struct FComboBoxOption final
{
public:
	class FString                                 Option_2_C6581DBE410A7C103FF128A81BE47388;         // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor)
	class FText                                   DisplayOptionName_5_71F6878D4F686E950AAE279207CBAB84; // 0x0010(0x0018)(Edit, BlueprintVisible)
};
static_assert(alignof(FComboBoxOption) == 0x000008, "Wrong alignment on FComboBoxOption");
static_assert(sizeof(FComboBoxOption) == 0x000028, "Wrong size on FComboBoxOption");
static_assert(offsetof(FComboBoxOption, Option_2_C6581DBE410A7C103FF128A81BE47388) == 0x000000, "Member 'FComboBoxOption::Option_2_C6581DBE410A7C103FF128A81BE47388' has a wrong offset!");
static_assert(offsetof(FComboBoxOption, DisplayOptionName_5_71F6878D4F686E950AAE279207CBAB84) == 0x000010, "Member 'FComboBoxOption::DisplayOptionName_5_71F6878D4F686E950AAE279207CBAB84' has a wrong offset!");

}

