#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DmgTypeExplosion_Vehicle

#include "Basic.hpp"

#include "TslGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DmgTypeExplosion_Vehicle.DmgTypeExplosion_Vehicle_C
// 0x0000 (0x0090 - 0x0090)
class UDmgTypeExplosion_Vehicle_C final : public UTslDamageType
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DmgTypeExplosion_Vehicle_C">();
	}
	static class UDmgTypeExplosion_Vehicle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDmgTypeExplosion_Vehicle_C>();
	}
};
static_assert(alignof(UDmgTypeExplosion_Vehicle_C) == 0x000008, "Wrong alignment on UDmgTypeExplosion_Vehicle_C");
static_assert(sizeof(UDmgTypeExplosion_Vehicle_C) == 0x000090, "Wrong size on UDmgTypeExplosion_Vehicle_C");

}

