#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HudMain

#include "Basic.hpp"

#include "HudMain_classes.hpp"
#include "HudMain_parameters.hpp"


namespace SDK
{

// Function HudMain.HudMain_C.ExecuteUbergraph_HudMain
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::ExecuteUbergraph_HudMain(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "ExecuteUbergraph_HudMain");

	Params::HudMain_C_ExecuteUbergraph_HudMain Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "Tick");

	Params::HudMain_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.CreateCheckReplayTimer
// (BlueprintCallable, BlueprintEvent)

void UHudMain_C::CreateCheckReplayTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "CreateCheckReplayTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.CheckReplayTimer
// (BlueprintCallable, BlueprintEvent)

void UHudMain_C::CheckReplayTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "CheckReplayTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.HideMapForReplay
// (BlueprintCallable, BlueprintEvent)

void UHudMain_C::HideMapForReplay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "HideMapForReplay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.OnShowWidget
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           WidgetName                                             (Parm, ZeroConstructor)
// bool                                    bShow                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::OnShowWidget(const class FString& WidgetName, bool bShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnShowWidget");

	Params::HudMain_C_OnShowWidget Parms{};

	Parms.WidgetName = std::move(WidgetName);
	Parms.bShow = bShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UHudMain_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.InitializeHUD
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsReplaying                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::InitializeHUD(bool bIsReplaying)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "InitializeHUD");

	Params::HudMain_C_InitializeHUD Parms{};

	Parms.bIsReplaying = bIsReplaying;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.OnPossessPawnChange
// (Public, BlueprintCallable, BlueprintEvent)

void UHudMain_C::OnPossessPawnChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnPossessPawnChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.GetHpRatio
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

float UHudMain_C::GetHpRatio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "GetHpRatio");

	Params::HudMain_C_GetHpRatio Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function HudMain.HudMain_C.Get_HealthMax_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UHudMain_C::Get_HealthMax_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "Get_HealthMax_Text_0");

	Params::HudMain_C_Get_HealthMax_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function HudMain.HudMain_C.Get_Health_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UHudMain_C::Get_Health_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "Get_Health_Text_0");

	Params::HudMain_C_Get_Health_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function HudMain.HudMain_C.Get_NumPlayersLeft_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UHudMain_C::Get_NumPlayersLeft_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "Get_NumPlayersLeft_Text_0");

	Params::HudMain_C_Get_NumPlayersLeft_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function HudMain.HudMain_C.Get_PlayerCoordinate_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UHudMain_C::Get_PlayerCoordinate_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "Get_PlayerCoordinate_Text_0");

	Params::HudMain_C_Get_PlayerCoordinate_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function HudMain.HudMain_C.OnKey_ToggleInventory
// (Public, BlueprintCallable, BlueprintEvent)

void UHudMain_C::OnKey_ToggleInventory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnKey_ToggleInventory");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.OnToggleMap
// (Public, BlueprintCallable, BlueprintEvent)

void UHudMain_C::OnToggleMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnToggleMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.Get_DebugInformation_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UHudMain_C::Get_DebugInformation_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "Get_DebugInformation_Text_0");

	Params::HudMain_C_Get_DebugInformation_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function HudMain.HudMain_C.GetFillColorAndOpacity_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

struct FLinearColor UHudMain_C::GetFillColorAndOpacity_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "GetFillColorAndOpacity_0");

	Params::HudMain_C_GetFillColorAndOpacity_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function HudMain.HudMain_C.Get_Vehicle_Health_Ratio
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

float UHudMain_C::Get_Vehicle_Health_Ratio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "Get_Vehicle_Health_Ratio");

	Params::HudMain_C_Get_Vehicle_Health_Ratio Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function HudMain.HudMain_C.OnKey_SystemMenuOrEscape
// (Public, BlueprintCallable, BlueprintEvent)

void UHudMain_C::OnKey_SystemMenuOrEscape()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnKey_SystemMenuOrEscape");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.Get_HealthBar_FillColorAndOpacity_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

struct FLinearColor UHudMain_C::Get_HealthBar_FillColorAndOpacity_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "Get_HealthBar_FillColorAndOpacity_0");

	Params::HudMain_C_Get_HealthBar_FillColorAndOpacity_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function HudMain.HudMain_C.OnButtonClick
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           ButotnName                                             (Parm, ZeroConstructor)

void UHudMain_C::OnButtonClick(const class FString& ButotnName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnButtonClick");

	Params::HudMain_C_OnButtonClick Parms{};

	Parms.ButotnName = std::move(ButotnName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.OnDisplayKilledMessage
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FDeathMessage                    DeathMessage                                           (Parm)

void UHudMain_C::OnDisplayKilledMessage(const struct FDeathMessage& DeathMessage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnDisplayKilledMessage");

	Params::HudMain_C_OnDisplayKilledMessage Parms{};

	Parms.DeathMessage = std::move(DeathMessage);

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.OnDisplaySystemMessage
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// ESystemMessageType                      MessageType                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FText                             Message                                                (Parm)

void UHudMain_C::OnDisplaySystemMessage(ESystemMessageType MessageType, const class FText& Message)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnDisplaySystemMessage");

	Params::HudMain_C_OnDisplaySystemMessage Parms{};

	Parms.MessageType = MessageType;
	Parms.Message = std::move(Message);

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.Get_VisibilityOnMatchState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

ESlateVisibility UHudMain_C::Get_VisibilityOnMatchState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "Get_VisibilityOnMatchState");

	Params::HudMain_C_Get_VisibilityOnMatchState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function HudMain.HudMain_C.Get_ParachuteText_Visibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

ESlateVisibility UHudMain_C::Get_ParachuteText_Visibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "Get_ParachuteText_Visibility_0");

	Params::HudMain_C_Get_ParachuteText_Visibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function HudMain.HudMain_C.OnNitifyHit
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DamagePercent                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// EDamageTypeCategory                     DamageTypeCategory                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::OnNitifyHit(float DamagePercent, EDamageTypeCategory DamageTypeCategory)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnNitifyHit");

	Params::HudMain_C_OnNitifyHit Parms{};

	Parms.DamagePercent = DamagePercent;
	Parms.DamageTypeCategory = DamageTypeCategory;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.GetBoostRatio
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

float UHudMain_C::GetBoostRatio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "GetBoostRatio");

	Params::HudMain_C_GetBoostRatio Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function HudMain.HudMain_C.On_BaseCanvas_Prepass_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          BoundWidget                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::On_BaseCanvas_Prepass_0(class UWidget* BoundWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "On_BaseCanvas_Prepass_0");

	Params::HudMain_C_On_BaseCanvas_Prepass_0 Parms{};

	Parms.BoundWidget = BoundWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.OnPrepass_VisibilityOnMatchState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          BoundWidget                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::OnPrepass_VisibilityOnMatchState(class UWidget* BoundWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnPrepass_VisibilityOnMatchState");

	Params::HudMain_C_OnPrepass_VisibilityOnMatchState Parms{};

	Parms.BoundWidget = BoundWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.OnPrepass_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          BoundWidget                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::OnPrepass_0(class UWidget* BoundWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnPrepass_0");

	Params::HudMain_C_OnPrepass_0 Parms{};

	Parms.BoundWidget = BoundWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.On_OnlySpectating_Prepass_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          BoundWidget                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::On_OnlySpectating_Prepass_0(class UWidget* BoundWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "On_OnlySpectating_Prepass_0");

	Params::HudMain_C_On_OnlySpectating_Prepass_0 Parms{};

	Parms.BoundWidget = BoundWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.Get_TextBlock_1_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UHudMain_C::Get_TextBlock_1_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "Get_TextBlock_1_Text_0");

	Params::HudMain_C_Get_TextBlock_1_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function HudMain.HudMain_C.On_InventoryShowHiddenCanvas_Prepass_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          BoundWidget                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::On_InventoryShowHiddenCanvas_Prepass_0(class UWidget* BoundWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "On_InventoryShowHiddenCanvas_Prepass_0");

	Params::HudMain_C_On_InventoryShowHiddenCanvas_Prepass_0 Parms{};

	Parms.BoundWidget = BoundWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.OnToggleInventory
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Bold                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::OnToggleInventory(bool Bold)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnToggleInventory");

	Params::HudMain_C_OnToggleInventory Parms{};

	Parms.Bold = Bold;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.IsCharacterAlive
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    IsAlive                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::IsCharacterAlive(bool* IsAlive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "IsCharacterAlive");

	Params::HudMain_C_IsCharacterAlive Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsAlive != nullptr)
		*IsAlive = Parms.IsAlive;
}


// Function HudMain.HudMain_C.On_SpectatingKeyInfo_Prepass_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          BoundWidget                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::On_SpectatingKeyInfo_Prepass_0(class UWidget* BoundWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "On_SpectatingKeyInfo_Prepass_0");

	Params::HudMain_C_On_SpectatingKeyInfo_Prepass_0 Parms{};

	Parms.BoundWidget = BoundWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.Get_KeyInfo_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UHudMain_C::Get_KeyInfo_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "Get_KeyInfo_Text_0");

	Params::HudMain_C_Get_KeyInfo_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function HudMain.HudMain_C.OnTogglePlayerList
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UHudMain_C::OnTogglePlayerList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnTogglePlayerList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.On_CharacterCanvas_Prepass_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          BoundWidget                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::On_CharacterCanvas_Prepass_0(class UWidget* BoundWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "On_CharacterCanvas_Prepass_0");

	Params::HudMain_C_On_CharacterCanvas_Prepass_0 Parms{};

	Parms.BoundWidget = BoundWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.OnPrepass_1
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          BoundWidget                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::OnPrepass_1(class UWidget* BoundWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnPrepass_1");

	Params::HudMain_C_OnPrepass_1 Parms{};

	Parms.BoundWidget = BoundWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.Get_Spectating_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UHudMain_C::Get_Spectating_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "Get_Spectating_Text_0");

	Params::HudMain_C_Get_Spectating_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function HudMain.HudMain_C.On_BlueZoneGpsWidget_RoundType_Prepass_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          BoundWidget                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::On_BlueZoneGpsWidget_RoundType_Prepass_0(class UWidget* BoundWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "On_BlueZoneGpsWidget_RoundType_Prepass_0");

	Params::HudMain_C_On_BlueZoneGpsWidget_RoundType_Prepass_0 Parms{};

	Parms.BoundWidget = BoundWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.OnShowCarePackageItemList
// (Public, BlueprintCallable, BlueprintEvent)

void UHudMain_C::OnShowCarePackageItemList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnShowCarePackageItemList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.OnKey_MapPressed
// (Public, BlueprintCallable, BlueprintEvent)

void UHudMain_C::OnKey_MapPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnKey_MapPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.OnKey_MapReleased
// (Public, BlueprintCallable, BlueprintEvent)

void UHudMain_C::OnKey_MapReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnKey_MapReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.OnMapShow
// (Public, BlueprintCallable, BlueprintEvent)

void UHudMain_C::OnMapShow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnMapShow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.OnMapHide
// (Public, BlueprintCallable, BlueprintEvent)

void UHudMain_C::OnMapHide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnMapHide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.OnToggleBattleList
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UHudMain_C::OnToggleBattleList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnToggleBattleList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.ShowReplayTimeline
// (Public, BlueprintCallable, BlueprintEvent)

void UHudMain_C::ShowReplayTimeline()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "ShowReplayTimeline");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.On_Name_Prepass_0
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          BoundWidget                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::On_Name_Prepass_0(class UWidget* BoundWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "On_Name_Prepass_0");

	Params::HudMain_C_On_Name_Prepass_0 Parms{};

	Parms.BoundWidget = BoundWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HudMain.HudMain_C.OnToggleOption
// (Public, BlueprintCallable, BlueprintEvent)

void UHudMain_C::OnToggleOption()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnToggleOption");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.InitForReplay
// (Public, BlueprintCallable, BlueprintEvent)

void UHudMain_C::InitForReplay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "InitForReplay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.OnKey_ReplayMenuOrEscape
// (Public, BlueprintCallable, BlueprintEvent)

void UHudMain_C::OnKey_ReplayMenuOrEscape()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "OnKey_ReplayMenuOrEscape");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.BindEventForMapClosing
// (Public, BlueprintCallable, BlueprintEvent)

void UHudMain_C::BindEventForMapClosing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "BindEventForMapClosing");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HudMain.HudMain_C.IsShowMapOrInventory
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    bIsShow                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::IsShowMapOrInventory(bool* bIsShow) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "IsShowMapOrInventory");

	Params::HudMain_C_IsShowMapOrInventory Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bIsShow != nullptr)
		*bIsShow = Parms.bIsShow;
}


// Function HudMain.HudMain_C.GetMiniMapType
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   Index_0                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UClass*                           MiniMapype                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHudMain_C::GetMiniMapType(int32 Index_0, class UClass** MiniMapype) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HudMain_C", "GetMiniMapType");

	Params::HudMain_C_GetMiniMapType Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (MiniMapype != nullptr)
		*MiniMapype = Parms.MiniMapype;
}

}

