#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ImportantMessageWidget

#include "Basic.hpp"

#include "ImportantMessageWidget_classes.hpp"
#include "ImportantMessageWidget_parameters.hpp"


namespace SDK
{

// Function ImportantMessageWidget.ImportantMessageWidget_C.ExecuteUbergraph_ImportantMessageWidget
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UImportantMessageWidget_C::ExecuteUbergraph_ImportantMessageWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ImportantMessageWidget_C", "ExecuteUbergraph_ImportantMessageWidget");

	Params::ImportantMessageWidget_C_ExecuteUbergraph_ImportantMessageWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ImportantMessageWidget.ImportantMessageWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UImportantMessageWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ImportantMessageWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ImportantMessageWidget.ImportantMessageWidget_C.GetFadeOutAnimation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidgetAnimation*                 Animation                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UImportantMessageWidget_C::GetFadeOutAnimation(class UWidgetAnimation** Animation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ImportantMessageWidget_C", "GetFadeOutAnimation");

	Params::ImportantMessageWidget_C_GetFadeOutAnimation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Animation != nullptr)
		*Animation = Parms.Animation;
}


// Function ImportantMessageWidget.ImportantMessageWidget_C.GetFadeInAnimation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidgetAnimation*                 Animation                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UImportantMessageWidget_C::GetFadeInAnimation(class UWidgetAnimation** Animation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ImportantMessageWidget_C", "GetFadeInAnimation");

	Params::ImportantMessageWidget_C_GetFadeInAnimation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Animation != nullptr)
		*Animation = Parms.Animation;
}

}

