#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MeleeWeaponStudio

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "TslGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MeleeWeaponStudio.MeleeWeaponStudio_C
// 0x0010 (0x0410 - 0x0400)
class AMeleeWeaponStudio_C final : public AItemStudio
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0400(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAsyncStaticMeshComponent*              AsyncStaticMesh;                                   // 0x0408(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor)

public:
	void ExecuteUbergraph_MeleeWeaponStudio(int32 EntryPoint);
	void SetItem(class UItem* Item);
	void UserConstructionScript();
	void OnLoaded();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MeleeWeaponStudio_C">();
	}
	static class AMeleeWeaponStudio_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMeleeWeaponStudio_C>();
	}
};
static_assert(alignof(AMeleeWeaponStudio_C) == 0x000010, "Wrong alignment on AMeleeWeaponStudio_C");
static_assert(sizeof(AMeleeWeaponStudio_C) == 0x000410, "Wrong size on AMeleeWeaponStudio_C");
static_assert(offsetof(AMeleeWeaponStudio_C, UberGraphFrame) == 0x000400, "Member 'AMeleeWeaponStudio_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AMeleeWeaponStudio_C, AsyncStaticMesh) == 0x000408, "Member 'AMeleeWeaponStudio_C::AsyncStaticMesh' has a wrong offset!");

}

