#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Motorbike_Seat_Driver

#include "Basic.hpp"

#include "VehicleSeatBase_Moto_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Motorbike_Seat_Driver.Motorbike_Seat_Driver_C
// 0x0000 (0x0458 - 0x0458)
class AMotorbike_Seat_Driver_C final : public AVehicleSeatBase_Moto_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Motorbike_Seat_Driver_C">();
	}
	static class AMotorbike_Seat_Driver_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMotorbike_Seat_Driver_C>();
	}
};
static_assert(alignof(AMotorbike_Seat_Driver_C) == 0x000008, "Wrong alignment on AMotorbike_Seat_Driver_C");
static_assert(sizeof(AMotorbike_Seat_Driver_C) == 0x000458, "Wrong size on AMotorbike_Seat_Driver_C");

}

