#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Uaz

#include "Basic.hpp"

#include "Uaz_classes.hpp"


namespace SDK
{

// Function Uaz.Uaz_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AUaz_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Uaz_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

