#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Uaz_Seat_PassengerBR

#include "Basic.hpp"

#include "VehicleSeatPassenger_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Uaz_Seat_PassengerBR.Uaz_Seat_PassengerBR_C
// 0x0000 (0x0458 - 0x0458)
class AUaz_Seat_PassengerBR_C final : public AVehicleSeatPassenger_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Uaz_Seat_PassengerBR_C">();
	}
	static class AUaz_Seat_PassengerBR_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AUaz_Seat_PassengerBR_C>();
	}
};
static_assert(alignof(AUaz_Seat_PassengerBR_C) == 0x000008, "Wrong alignment on AUaz_Seat_PassengerBR_C");
static_assert(sizeof(AUaz_Seat_PassengerBR_C) == 0x000458, "Wrong size on AUaz_Seat_PassengerBR_C");

}

