#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VehicleSeatDriver

#include "Basic.hpp"

#include "VehicleSeatBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass VehicleSeatDriver.VehicleSeatDriver_C
// 0x0000 (0x0458 - 0x0458)
class AVehicleSeatDriver_C : public AVehicleSeatBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VehicleSeatDriver_C">();
	}
	static class AVehicleSeatDriver_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVehicleSeatDriver_C>();
	}
};
static_assert(alignof(AVehicleSeatDriver_C) == 0x000008, "Wrong alignment on AVehicleSeatDriver_C");
static_assert(sizeof(AVehicleSeatDriver_C) == 0x000458, "Wrong size on AVehicleSeatDriver_C");

}

