#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VehicleSeatInfoWidget

#include "Basic.hpp"

#include "TslGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass VehicleSeatInfoWidget.VehicleSeatInfoWidget_C
// 0x0000 (0x02C0 - 0x02C0)
class UVehicleSeatInfoWidget_C final : public UVehicleSeatInfoBaseWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VehicleSeatInfoWidget_C">();
	}
	static class UVehicleSeatInfoWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVehicleSeatInfoWidget_C>();
	}
};
static_assert(alignof(UVehicleSeatInfoWidget_C) == 0x000008, "Wrong alignment on UVehicleSeatInfoWidget_C");
static_assert(sizeof(UVehicleSeatInfoWidget_C) == 0x0002C0, "Wrong size on UVehicleSeatInfoWidget_C");

}

