#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WidgetFunctionLibrary

#include "Basic.hpp"

#include "WidgetFunctionLibrary_classes.hpp"
#include "WidgetFunctionLibrary_parameters.hpp"


namespace SDK
{

// Function WidgetFunctionLibrary.WidgetFunctionLibrary_C.GetOwningShooterCharacter
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      UserWidget                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UObject*                          m_WorldContext                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class ATslCharacter*                    ShooterCharacter                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWidgetFunctionLibrary_C::GetOwningShooterCharacter(class UUserWidget* UserWidget, class UObject* m_WorldContext, class ATslCharacter** ShooterCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("WidgetFunctionLibrary_C", "GetOwningShooterCharacter");

	Params::WidgetFunctionLibrary_C_GetOwningShooterCharacter Parms{};

	Parms.UserWidget = UserWidget;
	Parms.m_WorldContext = m_WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (ShooterCharacter != nullptr)
		*ShooterCharacter = Parms.ShooterCharacter;
}

}

